# Generated by Django 4.2 on 2025-04-04 13:18

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'o campo deve ter no minimo 5 caracteres')])),
                ('especialidade', models.CharField(choices=[('CA', 'CARDIOLOGIA'), ('UR', 'UROLOGIA'), ('NEU', 'NEUROLOGIA')], max_length=15)),
                ('crm', models.CharField(max_length=7, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=15)),
                ('data', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)])),
                ('status', models.CharField(choices=[('CA', 'cancelado'), ('RE', 'realizado'), ('AG', 'agendado')], max_length=15)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
