# Generated by Django 4.2 on 2025-04-04 13:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('RE', 'realizado'), ('CA', 'cancelado'), ('AG', 'agendado')], max_length=15),
        ),
    ]
